let data={
    list:[
        {   
            hh:"福",
            tit:"那些不是春联的别称1",
            check:[
                "A:对联",
                "B:春帖",
                "C:门对",
                "D:喜联"
            ],
            sure:2
        },
        {
            hh:"禄",
            tit:"那些不是春联的别称2",
            check:[
                "A:对联",
                "B:春帖",
                "C:门对",
                "D:喜联"
            ],
            sure:3
        },{
            hh:"寿",
            tit:"那些不是春联的别称3",
            check:[
                "A:对联",
                "B:春帖",
                "C:门对",
                "D:喜联"
            ],
            sure:0
        },{
            hh:"旺",
            tit:"那些不是春联的别称4",
            check:[
                "A:对联",
                "B:春帖",
                "C:门对",
                "D:喜联"
            ],
            sure:3
        },{
            hh:"德",
            tit:"那些不是春联的别称5",
            check:[
                "A:对联",
                "B:春帖",
                "C:门对",
                "D:喜联"
            ],
            sure:1
        }
    ]
}
export default data