export const menu=[
    {
        subName:"课堂",
        subKey:"lesson",
        path:"/lesson",
        child:[
            {
                itemName:"address",
                key:"/lesson/address",
                path:"/address"
            },{
                itemName:"drag",
                key:"/lesson/drag",
                path:"/drag"
            },{
                itemName:"shopcar",
                key:"/lesson/shopcar",
                path:"/shopcar"
            },{
                itemName:"shopping",
                key:"/lesson/shopping",
                path:"/shopping"
            },{
                itemName:"monthA",
                key:"/lesson/monthA",
                path:"/monthA"
            },{
                itemName:"pay",
                key:"/lesson/pay",
                path:"/pay"
            },{
                itemName:"cinema",
                key:"/lesson/cinema",
                path:"/cinema"
            }
        ]
    },{
        subName:'考试',
        subKey:'exam',
        path:'/exam',
        child:[
            {
                itemName:"newyear",
                key:"/exam/newyear",
                path:"/newyear"
            }, {
                itemName:"examDay3",
                key:"/exam/examday3",
                path:"/examday3"
            }, {
                itemName:"examDay2",
                key:"/exam/examday2",
                path:"/examday2"
            }
        ]
    }
]