let datas={
    allPrice:0,
    allCheck:false,
    allnum:0,
    group:[
        {
            groupCheck:false,
            groupTittle:"洋酒",
            item:[
                {
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                },{
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                }, {
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                },{
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                }
            ]
        },{
            groupCheck:false,
            groupTittle:"红酒",
            item:[
                {
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                },{
                    itemCheck:false,
                    imgSrc:"",
                    title:"",
                    price:123,
                    num:1
                }
            ]
        }
    ]
}
export default datas